spring:
  application:
    name: aggregator-microservice
server:
  port: 8083
services:
  temperature-microservice: http://temperature-microservice:8081
  humidity-microservice: http://humidity-microservice:8082
aggregator:
  temperature-unit: ${TEMPERATURE_UNIT:L}
